### ISSUE TITLE
parametric text in details.php

### ISSUE THREAD

**Issue by ccomincini** [gtn/exalib#14]
Hi, first of all thenk you for sharing this fantastic piece of code. It's a very useful plugin.

I've noticed that in details.php there are 4 tect labels that need to be translatd but they are hardcoded and not parametric.:
`// ecco
if ($item->abstract) {
	echo '<h3>Abstract</h3>'.format_text($item->abstract).'</div>';
}
if ($item->background) {
	echo '<h3>Background</h3>'.format_text($item->background);
}
if ($item->methods) {
	echo '<h3>Methods</h3>'.format_text($item->methods);
}
if ($item->results) {
	echo '<h3>Results</h3>'.format_text($item->results);
}
if ($item->conclusion) {
	echo '<h3>Conclusion</h3>'.format_text($item->conclusion);
}`

I think that Anstract, Background, Methods, resluts and Conclusion must be parametric so that we can use languages code for translation. May you change this?
Thankyou

**Comment by dangerer** [comment]
Hi,
ok, we changed this to language dynamic strings
regards
Dietmar
